sudo: false
language: python
python:
- '3.6'

install: pip install tox-travis

script: tox

deploy:
  provider: script
  script: ".travis/dokku_deploy.sh"
  on:
    branch: master

before_install:
- openssl aes-256-cbc -K $encrypted_100edc2e68d6_key -iv $encrypted_100edc2e68d6_iv
  -in id_rsa.enc -out id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/id_rsa 
- ssh-add /tmp/id_rsa
- ssh-keyscan -t rsa -H pablogsal.science >> ~/.ssh/known_hosts
